device: mps

model:
  model_id: meta-llama/Llama-3.2-1B-Instruct
  use_fast: true

quantization:
  load_in_8bit: false
  load_in_4bit: false
  
generation:
  max_length: 1000
  temperature: 0.7
  top_p: 0.9
  format_prompt: true
