provider: openai
api_key: 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
model_name: gpt-4o

temperature: 0.7
max_tokens: 1000